### PR TITLE
fix: add info about db port

### PR DESCRIPTION
**Pull request by jiverson**

### CODE REVIEW

**Comment by dsifford** [comment]
Hey @jiverson thanks for the PR.

I'm wondering how this change would be helpful? Since we're not exposing port `3306` outside of the docker network, exposing it as 3307 shouldn't have any effect other thank just allowing you to access it from the host machine.

**Comment by jiverson** [comment]
Yeah it is just there for ones who had experienced this issue: https://github.com/visiblevc/wordpress-starter/issues/151#issuecomment-578519554 

If you would like to instead add it to the README or something up to you. But I was experiencing another issue which I am addressing in another PR I am working on. 

At the time I wasn't sure what exactly was going on.

**Comment by dsifford** [comment]
So looking at your comments in #172 ....

> I thought maybe it was my db so I switched to mysql which then would not initialize (obviously I had local mysql already using that port #171).

Even if you have mysql operating on your host on port 3306, mysql in the container will work just fine because it doesn't map to 3306 on the host, just in the container and its associated docker network. So changing mapping to 3307 on the host shouldn't have any affect on the init process.

**Comment by jiverson** [comment]
Yeah I can close this not a big deal honestly.

**Pull request closed without merging**
