### PR TITLE
Add user on database test

### PR DESCRIPTION
**Pull request by luiscoms**

### CODE REVIEW

**Comment by karellm** [comment]
Hi? Can you at least share your use case and why you need this for documentation purposes?

**Comment by dsifford** [comment]
Not sure how the dyssynchrony happened here, but I checked in #130 and the user flag exists there. 

So we can probably close this.

**Comment by luiscoms** [comment]
This is because #130 is not merged yet, you can merge this before #130

**Comment by luiscoms** [comment]
The username on my database is not root, so, the mysqlping command fail

**Comment by dsifford** [comment]
Sorry for the trouble. If you need a working implementation right this moment, you're free to fork the repo and build from the image directly.

If you can afford to wait just a bit longer, we'll be merging #130 soon. Building and pushing the images is non-trivial, so I'd prefer to avoid doing it twice in such a short amount of time.

**Pull request closed without merging**
