### PR TITLE
add certbot to both images for SSL cert automation

### PR DESCRIPTION
**Pull request by dsifford**
This PR simply adds certbot to both images so that users who choose to run the image in production can obtain and renew certificates easily.

To obtain new certificates, open an interactive session in the wordpress service, run `certbot --apache`, and then follow the prompts.

To renew certificates, open an interactive session in the wordpress service and run `certbot renew`.

Alternatively, you can set the renew task up as a cronjob which runs every 90 days.

There's not really a great way to add it into the build script because it requires user interaction using interactive terminal prompts.

Let me know what you think @karellm

### CODE REVIEW

**Comment by karellm** [comment]
This looks good to me! You can merge as you see fit :)

**Comment by dsifford** [comment]
Curious if you think it would be worth it to offload the cert automation to a separate service vs keeping it within the wordpress service?

Trade off would be separation of concerns vs ease of use. (Certbot requires python and a bunch of libraries to operate)

**Comment by karellm** [comment]
Both are fine imo, I really don't have a strong preference here.

**Comment by dsifford** [comment]
@karellm Cool. We'll keep as-is for now until someone complains.

Just updated the readme and changelog. Bumped to version 0.13.0. Gonna merge this into master now and push to Dockerhub. 👍

**Pull request merged**
